### ISSUE TITLE
Auto-hide the app menu on Windows

### ISSUE THREAD

**Issue by axfelix** [cutls/TheDesk#308]
Most Electron applications don't have many useful features in the default app menu (File, Edit, View, etc.), it takes up space, and it's fairly easy to hide by default in Electron code -- I think this would be a good option.

**Comment by cutls** [comment]
At 2019.1.16 update(15.8.0), TheDesk shows menu-bar on all platforms.
This is because some people do not use keyboard shortcuts, and it can show the current version('About' window) easily.
I know along Electron default, on Windows, it should be hidden(only on macOS, should be shown)... but this is custom menubar, so I won't change it.

If you do not like it takes up space, check `System Preferences` -> `Window frame` -> `hidden` on Setting.

Thank you for your issue.
